### PR TITLE
Switch Dagger 1.x from JavaWriter to JavaPoet.

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by swankjesse** [comment]
Right now Dagger wants Java 1.6 or better, and JavaPoet wants Java 1.8 or better. I'm tempted to meet in the middle, requiring Java 1.7 or better for Dagger's compiler, and making JavaPoet build-on Java 1.7 completely.

Also blocked on a JavaPoet release!

**Comment by adriancole** [comment]
A build floor of JDK 7 sounds sensible to me.

**Comment by JakeWharton** [comment]
:+1:

**Comment by swankjesse** [comment]
Updated to JavaPoet 1.0.

**Comment by JakeWharton** [comment]
_\*blinks\*_

**Pull request merged**
